//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquiposDeportivo
    {
        public int IdEquipo { get; set; }
        public string NombreEquipo { get; set; }
        public string Entrenador { get; set; }
        public string Fundacion { get; set; }
        public Nullable<int> CampeonatosGanados { get; set; }
        public Nullable<int> IdCiudad { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
    }
}
